server:
  port: 8081

spring:
  application:
    name: kafka.project
  kafka:
    bootstrap-servers:
      - 54.180.155.113:9092
      - 54.180.155.113:29092
      - 54.180.155.113:39092
    consumer:
      group-id: test-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 자동 커밋 설정
      enable-auto-commit: true
      # 오프셋 리셋 전략
      auto-offset-reset: earliest
      # 추가 설정
      properties:
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:emailDB
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: DEBUG
    com.business: INFO