spring:
  application:
    name: kafka.project
  kafka:
    bootstrap-servers:
      - 54.180.155.113:9092
      - 54.180.155.113:29092
      - 54.180.155.113:39092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      # 추가 설정
      properties:
        linger.ms: 0
        batch.size: 16384
        buffer.memory: 33554432
    # 커스텀 파티셔너 설정 (필요시)
    # producer:
        properties:
          partitioner.class: org.apache.kafka.clients.producer.RoundRobinPartitioner
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userDB
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: DEBUG
    com.business: INFO